# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

address_to_cartesian <- function(address_r, canvas_network_r, pixel_prefix) {
    .Call(`_ggip_address_to_cartesian`, address_r, canvas_network_r, pixel_prefix)
}

